# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api

# @name getChampions
GET {{baseUrl}}/
###

# @name getChampion
GET {{baseUrl}}/Lissandra
###

# @name createChampion
POST {{baseUrl}}/create
Content-Type: application/json


    {
    "id": "Splurge",
    "name": "Splurge",
    "title": "the Whale of the West",
    "lore": "Has to be number one on any leaderboard.",
    "allytips": "Don't steal his creeps. You wouldn't like it when you steal his creeps.",
    "enemytips": "Steal his creeps. Will tilt off the face of the universe. May cause excessive inflammatory statements and an aneurysm.",
    "tags": ["Basement Dweller"],
    "partype": "Money"
    }

###

# @name deleteChampion
DELETE {{baseUrl}}/63fd86fe872cdfeb72fb7251/delete
Content-Type: application/json
###

# @name updateChampion
PUT {{baseUrl}}/63f905574aac23f31caccb71/update
Content-Type: application/json

    {
        "title": "A Gigantic Problem"
    }

