# To use this file, insall the REST Client extension
# vscode:extension/humao.rest-client

# To switch environments:
#  - Ctrl+Alt+E(Cmd+Alt+E for macOS)
#  - Or `Rest Client: Switch Environment` from command palette

# You'll need to switch to either `local` or `vercel` to get started.

@baseUrl = {{host}}/api

# @name getChampions
GET {{baseUrl}}/
###

# @name getChampion
GET {{baseUrl}}/Lissandra
###

# @name createChampion
POST {{baseUrl}}/create
Content-Type: application/json


    {
    "id": "Zanca",
    "name": "Zanca",
    "title": "the Removed Godskin Brother",
    "lore": "Do whatever.",
    "allytips": "Don't touch his glasses.",
    "enemytips": "Touch his glasses.",
    "partype": "Coffee"
    }

###

# @name deleteChampion
DELETE {{baseUrl}}/63fcc388659a66bc56899cd5/delete
Content-Type: application/json
###

# @name updateChampion
PUT {{baseUrl}}/63f905574aac23f31caccb71/update
Content-Type: application/json

    {
        "title": "A Gigantic Problem"
    }

